spring:

  # GMail Properties
  mail:
    host: smtp.gmail.com
    port: 587
    username: your_email_id
    password: your_email_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true